services:
  app_proxy:
    image: getumbrel/app-proxy:v0.5.1
    restart: on-failure
    environment:
      APP_HOST: p2p-music_web_1
      APP_PORT: 3005
      PROXY_AUTH_WHITELIST: "/api/*"

  ipfs:
    image: ipfs/kubo:latest
    restart: unless-stopped
    entrypoint: ["/bin/sh","-ec","/start.sh"]
    environment:
      IPFS_PROFILE: server
    volumes:
      - ${APP_DATA_DIR}/ipfs:/data/ipfs
      - ${APP_DATA_DIR}/ipfs/start.sh:/start.sh:ro

  web:
    build:
      context: ./server
    restart: unless-stopped
    depends_on:
      - ipfs
    environment:
      PORT: 3005
      IPFS_API_URL: http://ipfs:5001
      MUSIC_DIR: /music
      STATE_DIR: /state
    volumes:
      - ${APP_DATA_DIR}/music:/music:ro
      - ${APP_DATA_DIR}/state:/state
